# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartcarAuthExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartcarAuthExample

  pod 'SmartcarAuth', '~> 1.0'

  # For accessing local pods uncomment the line below
  # pod 'SmartcarAuth', :path => "path/to/SmartcarAuth/"

end
