
language: objective-c
osx_image: xcode14.2
xcode_workspace: SmartcarAuth.xcworkspace
xcode_scheme: SmartcarAuth

git:
  submodules: true

before_install:
  - gem install xcov
  - gem install cocoapods

install:
  - pushd ./android-sdk
  - ./gradlew generateDummyFramework podPublishReleaseXCFramework
  - popd
  - rm Frameworks/* && cp -r android-sdk/smartcar-auth/build/cocoapods/publish/release/SmartcarFramework.xcframework Frameworks/SmartcarFramework.xcframework
  - pod install

script:
  - pod lib lint --verbose --allow-warnings
  - xcodebuild -workspace SmartcarAuth.xcworkspace -scheme SmartcarAuth -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild -workspace SmartcarAuth.xcworkspace -scheme SmartcarAuth -sdk iphonesimulator -destination 'platform=iOS Simulator,id=EBFABEDC-FB85-45BE-BC9F-8C6D6A1773ED,OS=16.0' build test
  # - xcov -w SmartcarAuth.xcworkspace -s SmartcarAuth -m 75 --only_project_targets

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  # create tag
  - git config --global user.email "ci@smartcar.com"
  - git config --global user.name "Travis CI User"
  - export pod_spec_tag=$(cat SmartcarAuth.podspec | grep '^\s*s.version' | sed "s/[[:blank:]]*s.version[[:blank:]]*=[[:blank:]]*'\(.*\)'/\1/g")
  - git tag -a v$pod_spec_tag -m "Travis Generated Tag"

  # create archive
  - git add Frameworks
  - git archive --format=tar.gz -o release.tar.gz $(git write-tree)

deploy:
  # releases will push the tag
  - provider: releases
    dpl_version: 1.10.16
    api_key: $GH_TOKEN
    file: "release.tar.gz"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    dpl_version: 1.10.16
    skip_cleanup: true
    script: pod trunk push SmartcarAuth.podspec --allow-warnings
    on:
      branch: master
