coverage:
  strict_yaml_branch: master
  status:
    # Commit statuses for the whole project
    project:
      default: false
      unit:
        target: 95%
        flags: "unit"

    # Commit statuses for each patch
    patch:
      default: false
      unit:
        flags: "unit"
  ignore:
    "SmartcarAuthTests"